"""
vault_builder.py — Specialized agent pipelines per note type

Disease:  KB/researcher → [patho_agent ∥ drug_agent] → analyzer → formatter
Drug:     KB/researcher → drug_agent → formatter
Approach: KB/researcher + symptom_mapper → analyzer → formatter
Lab:      KB/researcher + interpreter  → analyzer → formatter

KB = NotebookLM (primary) → researcher (fallback ถ้า KB ยังไม่มีเนื้อหา)
"""
import os
import sys
import time
import argparse
import concurrent.futures

from router import call_agent, load_prompt

# NotebookLM optional (graceful fallback ถ้ายังไม่ได้ตั้งค่า)
try:
    from notebooklm_client import query_notebook
    _KB_AVAILABLE = True
except (ImportError, Exception):
    _KB_AVAILABLE = False
    print("⚠️  NotebookLM not available — will use researcher as primary source")

# KG optional
try:
    from kg_query import ClinicalKG
    _KG_AVAILABLE = True
except (ImportError, FileNotFoundError):
    _KG_AVAILABLE = False

# Vault graph optional
try:
    from vault_graph import get_vault_context as _get_vault_context
    _VAULT_GRAPH_AVAILABLE = True
except ImportError:
    _VAULT_GRAPH_AVAILABLE = False
    def _get_vault_context(topics, **kw): return ""

_KB_MISS_MARKERS = ("[KB: no results", "[KB error", "[KB: no targets", "[ERROR")

# ─── Vault Topics ────────────────────────────────────────────────────────────

VAULT_TOPICS = {
    "diseases": [
        "Heart Failure", "ACS", "Atrial Fibrillation",
        "Pulmonary Embolism", "Hypertensive Crisis",
        "AECOPD", "Community Acquired Pneumonia",
        "Pneumothorax", "Pleural Effusion",
        "Acute Kidney Injury", "Chronic Kidney Disease",
        "Hyponatremia", "Hyperkalemia",
        "DKA", "HHS", "Hypothyroidism", "Thyroid Storm",
        "Sepsis", "UTI", "Meningitis",
    ],
    "approaches": [
        "Chest Pain", "Dyspnea", "Leg Edema",
        "Altered Consciousness", "Fever",
        "Jaundice", "Upper GI Bleed",
        "Hyponatremia Approach", "Hyperkalemia Approach",
        "Approach to On Call",
    ],
    "drugs": [
        "Furosemide", "Heparin", "Warfarin",
        "Ceftriaxone", "Piperacillin-Tazobactam",
        "Norepinephrine", "Insulin Drip",
        "Enoxaparin", "Alteplase",
        "Meropenem", "Vancomycin", "Azithromycin", "Levofloxacin",
        "Adrenaline", "Amiodarone", "Adenosine", "Nicardipine",
        "Omeprazole", "Octreotide",
        "Diazepam", "Lorazepam", "Phenytoin",
        "Salbutamol", "Hydrocortisone", "Dexamethasone",
        "Calcium Gluconate", "N-acetylcysteine",
    ],
    "labs": [
        "ABG Interpretation", "CBC Pattern",
        "LFT Pattern", "Electrolyte Disorders",
        "Coagulation Profile",
    ],
}

# ─── Templates ───────────────────────────────────────────────────────────────

DISEASE_TEMPLATE = """# {topic}

Tags: #disease #{specialty}

## Definition & Classification
...

## Pathophysiology
[mechanism ที่เชื่อม basic science → clinical]

## Clinical Presentation

**Pertinent Positives ที่ต้องถาม:**
- ...

**Pertinent Negatives สำคัญ:**
- ...

**Physical Exam:**
- ...

## DDx
| Diagnosis | Key differentiating feature |
|---|---|
| ... | ... |

## Investigation
- [test] → [purpose] → [expected result]

## Management
1. ...

## Attending Questions
**Q:** ...
**A:** ...

## Related
- [[...]]

---
*Generated by CaseFlow Vault Builder*
"""

DRUG_TEMPLATE = """# Drug - {topic}

Tags: #drug #{drug_class}

## Class & MOA
[mechanism → clinical effect]

## Indications
- ...

## Dosing
| Indication | Dose | Route | Frequency |
|---|---|---|---|
| ... | ... | ... | ... |

## Dose Adjustment
- Renal: ...
- Hepatic: ...

## Key Side Effects
| SE | กลไก | Monitor |
|---|---|---|
| ... | ... | ... |

## Drug Interactions
- ...

## Attending Questions
**Q:** ...
**A:** ...

## Related
- [[...]]

---
*Generated by CaseFlow Vault Builder*
"""

APPROACH_TEMPLATE = """# Approach - {topic}

Tags: #approach #{symptom}

## Characterize ก่อนเสมอ
| ถามอะไร | ทำไม |
|---|---|
| ... | ... |

## DDx Framework

### 🟢 Likely
| Dx | Key clue | Differentiating feature |
|---|---|---|

### 🟡 Possible
| Dx | Key clue | Differentiating feature |
|---|---|---|

### 🔴 Don't Miss ⚠️
| Dx | Why dangerous | Clue to catch it |
|---|---|---|

## Key Pertinent Negatives
- ❌ ...

## PE ที่ต้องทำ
- ...

## First-line Investigation
- ...

## Attending Questions
**Q:** ...
**A:** ...

## Related
- [[...]]

---
*Generated by CaseFlow Vault Builder*
"""

LAB_TEMPLATE = """# Lab - {topic}

Tags: #lab #{lab_type}

## Normal Values
- ...

## When to Order
- ...

## Interpretation

### Elevated / High
| Cause | Mechanism | Clinical clue |
|---|---|---|

### Decreased / Low
| Cause | Mechanism | Clinical clue |
|---|---|---|

## Pattern Recognition
| Pattern | Interpretation | Think of |
|---|---|---|
| ... | ... | ... |

## Pitfalls & False Results
- ...

## Attending Questions
**Q:** ...
**A:** ...

## Related
- [[...]]

---
*Generated by CaseFlow Vault Builder*
"""

TEMPLATES = {
    "diseases":  DISEASE_TEMPLATE,
    "approaches": APPROACH_TEMPLATE,
    "drugs":     DRUG_TEMPLATE,
    "labs":      LAB_TEMPLATE,
}

SPECIALTY_MAP = {
    "Heart Failure": "cardiology", "ACS": "cardiology",
    "Atrial Fibrillation": "cardiology", "Pulmonary Embolism": "cardiology",
    "Hypertensive Crisis": "cardiology",
    "AECOPD": "pulmonology", "Community Acquired Pneumonia": "pulmonology",
    "Pneumothorax": "pulmonology", "Pleural Effusion": "pulmonology",
    "Acute Kidney Injury": "nephrology", "Chronic Kidney Disease": "nephrology",
    "Hyponatremia": "nephrology", "Hyperkalemia": "nephrology",
    "DKA": "endocrine", "HHS": "endocrine",
    "Hypothyroidism": "endocrine", "Thyroid Storm": "endocrine",
    "Sepsis": "infectious", "UTI": "infectious", "Meningitis": "infectious",
}

# ─── Parallel helper ─────────────────────────────────────────────────────────

def _parallel(calls: list[tuple]) -> list[str]:
    """Run agent calls concurrently. calls = [(name, prompt, system), ...]"""
    with concurrent.futures.ThreadPoolExecutor(max_workers=len(calls)) as ex:
        futures = [ex.submit(call_agent, name, prompt, system) for name, prompt, system in calls]
        return [f.result() for f in futures]


def _query_knowledge(topic: str, focus: str) -> tuple[str, str]:
    """
    ดึงข้อมูลจาก 2 แหล่ง:
    1. NotebookLM (KB) — primary, ใช้ความรู้ที่เราเพิ่มเองไว้
    2. researcher (Gemini + grounding) — fallback ถ้า KB ยังไม่มีเนื้อหา

    Returns: (kb_result, research_result) — อาจเป็นว่างถ้าหาไม่เจอ
    """
    kb_result = ""
    if _KB_AVAILABLE:
        try:
            result = query_notebook("medicine", f"สรุปข้อมูลเรื่อง {topic}: {focus}")
            if result and not any(m in result for m in _KB_MISS_MARKERS):
                kb_result = result
                print(f"  ✅ KB hit — NotebookLM")
            else:
                print(f"  ℹ️  KB miss — falling back to researcher")
        except Exception as e:
            print(f"  ⚠️  KB error: {e} — falling back to researcher")

    research_result = ""
    if not kb_result:
        try:
            result = call_agent(
                "researcher",
                system=load_prompt("researcher") or "",
                prompt=(
                    f"ค้นหาข้อมูล {focus} เรื่อง {topic} สำหรับ ward medicine ปี 4\n"
                    f"เน้น: current guidelines, key evidence, สิ่งที่ต้องรู้บน ward\n"
                    f"สรุปเป็นข้อๆ ภาษาอังกฤษ/ไทยผสม ไม่เกิน 800 คำ"
                ),
            )
            research_result = "" if result.startswith("[ERROR") else result
        except Exception as e:
            print(f"  ⚠️  researcher failed: {e}")

    return kb_result, research_result


def _best_knowledge(kb: str, research: str) -> str:
    """เลือกแหล่งที่ดีที่สุด — KB ก่อน ถ้าว่างใช้ research"""
    return kb or research or ""


# ─── Type-specific pipelines ─────────────────────────────────────────────────

def _generate_disease_note(topic: str, template: str, kg_context: str) -> str:
    """
    Disease: researcher → [patho_agent ∥ drug_agent] → analyzer → formatter
    Claude calls: 3 (2 parallel + 1 sequential) | Gemini: 1
    """
    print(f"  [1/4] knowledge — NotebookLM → researcher fallback...")
    kb, research = _query_knowledge(
        topic,
        "definition, classification, epidemiology, current guidelines (AHA/ESC/WHO/KDIGO), "
        "landmark trials, key pathophysiology"
    )
    knowledge = _best_knowledge(kb, research)

    print(f"  [2/4] patho_agent + drug_agent — parallel...")
    patho_result, drug_result = _parallel([
        (
            "patho_agent",
            (
                f"อธิบาย Pathophysiology ของ {topic} สำหรับนิสิตแพทย์ปี 4:\n"
                f"- กลไกระดับ molecular/cellular → organ dysfunction → clinical signs\n"
                f"- ทำไมแต่ละ symptom/sign จึงเกิด (เชื่อม mechanism)\n"
                f"- Key mediators / pathways สำคัญ\n"
                f"กระชับ ไม่เกิน 400 คำ\n\n"
                f"Context:\n{knowledge[:1500]}"
            ),
            "",
        ),
        (
            "drug_agent",
            (
                f"ยาสำคัญในการรักษา {topic} บน ward medicine:\n"
                f"- ยาแต่ละตัว: class | dose range | route | key SE | contraindication\n"
                f"- Drug interactions สำคัญ 2-3 คู่\n"
                f"- Monitoring parameters\n"
                f"เน้นยาที่ใช้จริงบน ward ไม่ใช่ทุกตัวที่มีในโลก\n\n"
                f"Context:\n{knowledge[:1500]}"
            ),
            "",
        ),
    ])

    print(f"  [3/4] analyzer — synthesize full note...")
    content = call_agent(
        "analyzer",
        system=(
            "คุณคืออาจารย์อายุรศาสตร์ระดับ Attending "
            "สร้างคู่มือ ward ที่ครบถ้วน แม่นยำ กระชับ "
            "เน้นสิ่งที่ใช้ได้จริง ไม่ใช่ textbook ท่องจำ"
        ),
        prompt=f"""สร้าง Obsidian note เรื่อง "{topic}" โดยใช้ข้อมูลที่รวบรวมมาแล้ว

=== Template ===
{template}

=== Knowledge Base ===
{knowledge[:2000] if knowledge else "(ใช้ความรู้ทั่วไป)"}

=== Pathophysiology ===
{patho_result}

=== Key Drugs ===
{drug_result}

=== KG Context ===
{kg_context or "(ไม่มี)"}

=== คำสั่ง ===
- เติมทุก section — ห้ามเว้นว่าง ห้ามใส่ "..."
- Clinical Presentation: อิง patho อธิบายว่าทำไม sign/symptom นั้นจึงเกิด
- DDx table: ระบุ key differentiating feature จาก patho/investigation
- Management: ใช้ dose จาก drug_agent (ห้าม hallucinate dose)
- Attending Questions: 3 ข้อที่อาจารย์ถามจริงบน ward พร้อมคำตอบที่ลึก
- ใส่ [[wikilinks]] ทุกครั้งที่กล่าวถึงโรค ยา หรือ approach อื่น
""",
    )

    print(f"  [4/4] formatter — Obsidian format...")
    return call_agent("formatter", system=load_prompt("formatter_obsidian"), prompt=content)


def _generate_drug_note(topic: str, template: str, kg_context: str) -> str:
    """
    Drug: researcher → drug_agent → formatter
    Claude calls: 2 | Gemini: 1
    """
    print(f"  [1/3] knowledge — NotebookLM → researcher fallback...")
    kb, research = _query_knowledge(
        topic,
        "mechanism of action, pharmacokinetics, indications, dosing guidelines, clinical evidence"
    )
    knowledge = _best_knowledge(kb, research)

    print(f"  [2/3] drug_agent — comprehensive drug profile...")
    content = call_agent(
        "drug_agent",
        system=(
            "คุณคือเภสัชกรคลินิกและอาจารย์แพทย์เชี่ยวชาญด้านยา "
            "ข้อมูล dose ต้องถูกต้อง แม่นยำ ห้าม hallucinate "
            "เน้นสิ่งที่นิสิตปี 4 ต้องรู้และใช้จริงบน ward"
        ),
        prompt=f"""สร้าง drug profile ครบถ้วนสำหรับ {topic}

=== Template ===
{template}

=== Pharmacology Context ===
{knowledge[:2500] if knowledge else "(ใช้ความรู้ทั่วไป)"}

=== KG Context ===
{kg_context or "(ไม่มี)"}

=== คำสั่ง ===
- MOA: อธิบาย mechanism → clinical effect อย่างชัดเจน
- Dosing table: ครบทุก indication, dose range, route, frequency
- Dose adjustment: renal + hepatic (ถ้าเกี่ยวข้อง)
- Key SE table: SE ที่พบบ่อย + SE อันตราย + กลไก + monitoring
- Drug interactions: อย่างน้อย 3 คู่สำคัญ + กลไก + วิธีจัดการ
- Attending Questions: 3 ข้อที่อาจารย์ถามเรื่องยานี้บ่อย พร้อมคำตอบ
- ใส่ [[wikilinks]] ทุกครั้งที่กล่าวถึงโรคหรือยาอื่น
""",
    )

    print(f"  [3/3] formatter — Obsidian format...")
    return call_agent("formatter", system=load_prompt("formatter_obsidian"), prompt=content)


def _generate_approach_note(topic: str, template: str, kg_context: str) -> str:
    """
    Approach: symptom_mapper → analyzer → formatter
    Claude calls: 1 | Gemini: 2
    """
    print(f"  [1/3] knowledge + symptom_mapper — parallel...")
    kb, research = _query_knowledge(
        topic,
        "DDx framework, systematic approach, key questions, red flags, investigations"
    )
    knowledge = _best_knowledge(kb, research)
    # symptom_mapper รันต่อจากนั้น (ได้ KB context แล้ว)
    mapper_result = call_agent(
        "symptom_mapper",
        system=load_prompt("symptom_mapper") or "",
        prompt=(
            f"วาง systematic approach สำหรับ {topic}:\n"
            f"- คำถามสำคัญที่ต้องถาม เพื่อ characterize อาการ\n"
            f"- DDx แบ่ง: Likely / Possible / Don't Miss (ระบุ Red flags)\n"
            f"- PE ที่ต้องทำ + ผลที่คาดหวัง\n"
            f"- First-line investigations + เหตุผล\n"
            f"สรุปเป็น framework ที่ใช้บน ward ได้ทันที กระชับ ไม่เกิน 500 คำ\n\n"
            f"{'Knowledge Base Context:' + chr(10) + knowledge[:1500] if knowledge else ''}"
        ),
    )

    print(f"  [2/3] analyzer — synthesize approach note...")
    content = call_agent(
        "analyzer",
        system=(
            "คุณคืออาจารย์อายุรศาสตร์เชี่ยวชาญ clinical reasoning "
            "สร้าง approach note ที่ใช้ได้จริงบน ward กระชับ เน้น pattern recognition"
        ),
        prompt=f"""สร้าง Obsidian note: Approach to {topic}

=== Template ===
{template}

=== DDx Framework (symptom_mapper) ===
{mapper_result}

=== KG Context ===
{kg_context or "(ไม่มี)"}

=== คำสั่ง ===
- ใช้ framework จาก symptom_mapper เป็นโครงหลัก
- Characterize table: ทุกคำถามต้องมีเหตุผลว่าถามทำไม
- Don't Miss section: ต้องระบุ why dangerous + clue ที่จะจับได้
- Key Pertinent Negatives: ระบุว่าถ้าไม่มีอาการนี้ตัด DDx อะไรออก
- Attending Questions: 3 ข้อที่อาจารย์ถาม approach นี้บ่อย
- ใส่ [[wikilinks]] ทุกครั้งที่กล่าวถึงโรค ยา หรือ approach อื่น
""",
    )

    print(f"  [3/3] formatter — Obsidian format...")
    return call_agent("formatter", system=load_prompt("formatter_obsidian"), prompt=content)


def _generate_lab_note(topic: str, template: str, kg_context: str) -> str:
    """
    Lab: interpreter → analyzer → formatter
    Claude calls: 1 | Gemini: 2
    """
    print(f"  [1/3] knowledge + interpreter...")
    kb, research = _query_knowledge(
        topic,
        "normal values, causes of abnormality, clinical interpretation, patterns, pitfalls"
    )
    knowledge = _best_knowledge(kb, research)
    interp_result = call_agent(
        "interpreter",
        system=load_prompt("interpreter") or "",
        prompt=(
            f"สร้าง interpretation framework สำหรับ {topic}:\n"
            f"- Normal values + reference range (ระบุ unit)\n"
            f"- Causes ของ elevated/decreased + กลไกแต่ละอัน\n"
            f"- Pattern recognition: pattern ไหน → นึกถึงอะไร\n"
            f"- Pitfalls + false positive/negative ที่สำคัญ\n"
            f"เน้น clinical relevance บน ward กระชับ ไม่เกิน 500 คำ\n\n"
            f"{'Knowledge Base Context:' + chr(10) + knowledge[:1500] if knowledge else ''}"
        ),
    )

    print(f"  [2/3] analyzer — synthesize lab note...")
    content = call_agent(
        "analyzer",
        system=(
            "คุณคืออาจารย์อายุรศาสตร์เชี่ยวชาญ lab interpretation "
            "ข้อมูลต้องถูกต้อง แม่นยำ เน้น clinical relevance ไม่ใช่ basic science ล้วนๆ"
        ),
        prompt=f"""สร้าง Obsidian note สำหรับ {topic}

=== Template ===
{template}

=== Interpretation Framework (interpreter) ===
{interp_result}

=== KG Context ===
{kg_context or "(ไม่มี)"}

=== คำสั่ง ===
- ใช้ framework จาก interpreter เป็นโครงหลัก
- Elevated/Low tables: ต้องมี cause + mechanism + clinical clue ครบทุกแถว
- Pattern Recognition table: เน้น pattern ที่พบบ่อยบน ward
- Pitfalls: เน้น false results ที่หลอกได้บ่อยและ clinical impact
- Attending Questions: 3 ข้อที่อาจารย์ถามเรื่อง lab นี้
- ใส่ [[wikilinks]] ทุกครั้งที่กล่าวถึงโรค ยา หรือ lab อื่น
""",
    )

    print(f"  [3/3] formatter — Obsidian format...")
    return call_agent("formatter", system=load_prompt("formatter_obsidian"), prompt=content)


# ─── Dispatcher ──────────────────────────────────────────────────────────────

_GENERATORS = {
    "diseases":  _generate_disease_note,
    "drugs":     _generate_drug_note,
    "approaches": _generate_approach_note,
    "labs":      _generate_lab_note,
}


def generate_note(topic: str, topic_type: str, kg: "ClinicalKG" = None) -> str:
    # KG context from PrimeKG
    kg_context = ""
    if kg:
        try:
            kg_context = kg.get_kg_context(topic)
        except Exception:
            pass

    # Vault graph context — pull content from existing related notes (1 hop)
    vault_context = ""
    if _VAULT_GRAPH_AVAILABLE:
        try:
            vault_context = _get_vault_context([topic], depth=1, max_total_chars=3000)
            if vault_context:
                print(f"  [vault] {len(vault_context)} chars from linked notes")
        except Exception:
            pass

    # Combine both as structured context
    combined_context = "\n\n".join(filter(None, [kg_context, vault_context]))

    template = TEMPLATES.get(topic_type, DISEASE_TEMPLATE)
    specialty = SPECIALTY_MAP.get(topic, topic_type)
    template_filled = template.format(
        topic=topic,
        specialty=specialty,
        drug_class=specialty,
        symptom=topic.lower().replace(" ", "_"),
        lab_type=topic.lower().replace(" ", "_"),
    )

    generator = _GENERATORS.get(topic_type, _generate_disease_note)
    return generator(topic, template_filled, combined_context)


# ─── build_vault + MOC (unchanged logic) ─────────────────────────────────────

def build_vault(output_dir: str, topics: dict = None, kg: "ClinicalKG" = None,
                delay: float = 2.0, resume_from: str = None):
    if topics is None:
        topics = VAULT_TOPICS

    os.makedirs(output_dir, exist_ok=True)

    FOLDER_MAP = {
        "diseases":  "02 - Diseases",
        "drugs":     "03 - Drugs",
        "labs":      "04 - Labs",
        "approaches": "08 - Approaches",
    }

    total = sum(len(t) for t in topics.values())
    current = 0
    found_resume = resume_from is None
    errors = []

    for topic_type, topic_list in topics.items():
        folder = os.path.join(output_dir, FOLDER_MAP.get(topic_type, topic_type.capitalize()))
        os.makedirs(folder, exist_ok=True)

        for topic in topic_list:
            current += 1

            if not found_resume:
                if topic == resume_from:
                    found_resume = True
                else:
                    print(f"  ⏭️  Skipping {topic} (resume mode)")
                    continue

            filename = topic.replace(" ", "_") + ".md"
            filepath = os.path.join(folder, filename)

            if os.path.exists(filepath):
                print(f"[{current}/{total}] ⏭️  {topic} — already exists")
                continue

            print(f"\n[{current}/{total}] 📝 {topic} ({topic_type})")

            try:
                content = generate_note(topic, topic_type, kg)
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write(content)
                print(f"  ✅ Saved: {filepath}")
            except Exception as e:
                print(f"  ❌ ERROR: {e}")
                errors.append(f"{topic}: {e}")
                continue

            time.sleep(delay)

    _build_moc(output_dir, topics)

    print(f"\n{'='*50}")
    print(f"✅ Vault built: {output_dir}")
    print(f"   Topics: {total} | Errors: {len(errors)}")
    for e in errors:
        print(f"   ✗ {e}")


def _build_moc(output_dir: str, topics: dict):
    lines = ["# 🗺️ Map of Content — Ward Medicine\n",
             "*Auto-generated by CaseFlow Vault Builder*\n"]
    for topic_type, topic_list in topics.items():
        lines.append(f"\n## {topic_type.capitalize()}\n")
        for topic in topic_list:
            lines.append(f"- [[{topic}]]")
    lines += ["\n\n---", "*Generated by CaseFlow Vault Builder*"]
    with open(os.path.join(output_dir, "MOC.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"  ✅ MOC updated")


# ─── CLI ─────────────────────────────────────────────────────────────────────

if __name__ == "__main__":
    if sys.stdout.encoding != "utf-8":
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(description="CaseFlow Vault Builder")
    parser.add_argument("-o", "--output", default=r"C:\Users\USER\OneDrive\Desktop\caseflow\obsidian")
    parser.add_argument("--delay", type=float, default=2.0)
    parser.add_argument("--resume", type=str, default=None)
    parser.add_argument("--no-kg", action="store_true")
    parser.add_argument("--only", type=str, default=None,
                        help="diseases | approaches | drugs | labs")
    parser.add_argument("--topic", type=str, default=None)
    parser.add_argument("--type", type=str, default="diseases")
    parser.add_argument("--all", action="store_true")
    parser.add_argument("--from-json", type=str, default=None,
                        help="Path to JSON file: {type: [topics]} — used by gap_finder")
    args = parser.parse_args()

    kg = None
    if not args.no_kg and _KG_AVAILABLE:
        try:
            kg = ClinicalKG()
        except FileNotFoundError as e:
            print(f"⚠️  KG not available: {e}")

    if args.from_json:
        import json as _json
        with open(args.from_json, "r", encoding="utf-8") as _f:
            topics = _json.load(_f)
        print(f"📂 Loaded topics from {args.from_json}")
    elif args.topic:
        topics = {args.type: [args.topic]}
    elif args.only:
        if args.only not in VAULT_TOPICS:
            print(f"❌ Unknown type: {args.only}. Available: {', '.join(VAULT_TOPICS)}")
            sys.exit(1)
        topics = {args.only: VAULT_TOPICS[args.only]}
    elif args.all:
        topics = VAULT_TOPICS
    else:
        print("❌ ระบุ target: --topic / --only / --all")
        sys.exit(1)

    n = sum(len(t) for t in topics.values())
    print(f"🏗️  CaseFlow Vault Builder")
    print(f"   Output : {args.output}")
    print(f"   Topics : {n}")
    print(f"   KG     : {'enabled' if kg else 'disabled'}")
    print()

    build_vault(args.output, topics=topics, kg=kg, delay=args.delay, resume_from=args.resume)
